config/routes.rb
UserCenter::Application.routes.draw do
  get "/get_login_ticket.json" => "sso_api#get_login_ticket"
  get "/get_service_ticket.json" => "sso_api#get_service_ticket"

  match "/serviceValidate" => "validators#serviceValidate"
  match "/proxyValidate" => "validators#proxyValidate"

  resources :sessions
  resources :password_resets
  resource :user
  get "/user/activate/:token" => "users#activate", :as => :activate

  match 'login' => 'sessions#new', :as => :login
  match 'logout' => 'sessions#destroy', :as => :logout

  # resource :oauth do
  #   get :callback
  # end
  # match "oauth/:provider" => "oauths#oauth", :as => :auth_at_provider

  root :to => 'sessions#new'

  # match ':controller(/:action(/:id(.:format)))'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ASICS UserCenter</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tag %>
  <script src="http://www.asics.co.uk/feeds/clean_header_footer.js" type="text/javascript"></script>
</head>
<body>
<!-- <div id="holder"> -->
    <div id="top">
      <div id="top_container" class="clearfix">
        <% if current_user %>
          <ul id="navigation">
            <li><a href="#" ><%= current_user.email %></a></li>
            <li class="vr_top"></li>
            <li><%= link_to("Logout", logout_path) %></li>
          </ul>
        <% else %>
          <ul id="navigation">
            <li><%= link_to "Register", new_user_path %></li>
            <li class="vr_top"></li>
            <li><%= link_to "Login", :login %></li>
            <%#= link_to 'Login with Twitter', auth_at_provider_path(:provider => :twitter) %>
            <%#= link_to 'Login with Facebook', auth_at_provider_path(:provider => :facebook) %>
          </ul>
          <%#= link_to("Login", "#{CASClient::Frameworks::Rails::Filter.config[:login_url]}?service=#{request.url}") %>
        <% end %>
      </div>
    </div>

    <div id="wrapper">
      <header id="header">
        <h1><a href="#" id="logo">ASICS</a></h1>
      </header>
      <section id="main">
        <p id="notice"><%= notice %></p>
        <p id="alert"><%= alert %></p>

        <%= yield %>
      </section>
    </div>

    <!-- </div> -->
    <script type="text/javascript">
      // if (typeof minisite !== "undefined") minisite.write('footer');
    </script>
</body>
</html>

app/views/layouts/redirecting.html.erb
<html>
  <head>
    <title>User Center</title>
    <noscript><meta http-equiv="refresh" content="5; url=&#39;<%= @back_url %>&#39;"></noscript>
    <script type="text/javascript">
      function doRedirect() {
        location.replace("<%= @back_url %>");
      }
    </script>
  </head>
  <body onload="doRedirect()">
    <%= yield %>
  </body>
</html>